import type { ActivityItem, Album, Artist, Song } from "./types";

const daysAgo = (d: number, hours = 0) =>
  new Date(Date.now() - d * 86_400_000 - hours * 3_600_000).toISOString();

export const ARTISTS: Artist[] = [
  {
    id: "u-ben",
    username: "ben",
    displayName: "Ben Gibbard",
    bio: "Melodies first. Sending tapes across the country since forever.",
    avatarHue: 210,
    location: "Seattle, WA",
    daw: "Ableton Live 12",
  },
  {
    id: "u-jenny",
    username: "jenny",
    displayName: "Jenny Lewis",
    bio: "Vocals, lyrics, late-night overdubs. Open the freeze, not the hard drive.",
    avatarHue: 28,
    location: "Los Angeles, CA",
    daw: "Ableton Live 12",
  },
  {
    id: "u-jimmy",
    username: "jimmy",
    displayName: "Jimmy Tamborello",
    bio: "Synths, clicks, glitches. Max for Live experiments welcome.",
    avatarHue: 265,
    location: "Los Angeles, CA",
    daw: "Ableton Live 12 + Max",
  },
  {
    id: "u-taylor",
    username: "taylor",
    displayName: "Taylor R.",
    bio: "Producer / mixer. If it isn't frozen, I can't open it on the road.",
    avatarHue: 155,
    location: "Austin, TX",
    daw: "Ableton Live 12",
  },
  {
    id: "u-maya",
    username: "maya",
    displayName: "Maya Chen",
    bio: "Bedroom pop, field recordings, and shared folders that finally make sense.",
    avatarHue: 340,
    location: "Brooklyn, NY",
    daw: "Logic + Ableton",
  },
];

export const SONGS: Song[] = [
  {
    id: "song-such-great-heights",
    ownerId: "u-ben",
    slug: "such-great-heights",
    title: "Such Great Heights",
    description:
      "The modern tape-in-the-mail workflow. Ben starts the bones in Seattle; Jimmy answers with electronics from L.A. Every push freezes third-party chains so either side can open the set without matching plug-in racks.",
    visibility: "public",
    daw: "ableton",
    bpm: 175,
    key: "D major",
    timeSignature: "4/4",
    albumId: "album-give-up",
    tags: ["indie-electronic", "collaboration", "postal-service"],
    createdAt: daysAgo(120),
    updatedAt: daysAgo(1, 3),
    starCount: 1842,
    forkCount: 96,
    coverHue: 200,
    freezeReady: false,
    pluginIds: [
      "ableton-eq8",
      "ableton-compressor",
      "ableton-operator",
      "ableton-wavetable",
      "ableton-drum-rack",
      "serum2",
      "valhalla-vintageverb",
      "fabfilter-pro-q3",
      "soundtoys-echoboy",
      "max-for-live-grain",
      "rc20",
    ],
    collaborators: [
      { userId: "u-ben", role: "owner", joinedAt: daysAgo(120) },
      { userId: "u-jimmy", role: "producer", joinedAt: daysAgo(118) },
      { userId: "u-jenny", role: "writer", joinedAt: daysAgo(90) },
    ],
    tracks: [
      {
        id: "t-drums",
        name: "Kit_Main",
        kind: "midi",
        color: "#c45c26",
        freezeStatus: "frozen",
        plugins: [
          { pluginId: "ableton-drum-rack", slot: 0, enabled: true, status: "frozen-away" },
          { pluginId: "ableton-compressor", slot: 1, enabled: true, status: "ok" },
        ],
        durationBars: 96,
      },
      {
        id: "t-bass",
        name: "Bass_Analog",
        kind: "midi",
        color: "#2f6fed",
        freezeStatus: "live",
        plugins: [
          { pluginId: "ableton-operator", slot: 0, enabled: true, status: "ok" },
          { pluginId: "fabfilter-pro-q3", slot: 1, enabled: true, status: "ok" },
        ],
        durationBars: 96,
        notes: "Jimmy: leave the Operator patch editable for now",
      },
      {
        id: "t-lead",
        name: "Lead_Heights",
        kind: "midi",
        color: "#7c3aed",
        freezeStatus: "live",
        plugins: [
          { pluginId: "serum2", slot: 0, enabled: true, status: "ok" },
          { pluginId: "soundtoys-echoboy", slot: 1, enabled: true, status: "ok" },
          { pluginId: "valhalla-vintageverb", slot: 2, enabled: true, status: "ok" },
        ],
        durationBars: 64,
        notes: "Requires Serum 2 — freeze before Taylor can open",
      },
      {
        id: "t-pads",
        name: "Pad_Cloud",
        kind: "midi",
        color: "#0d9488",
        freezeStatus: "live",
        plugins: [
          { pluginId: "ableton-wavetable", slot: 0, enabled: true, status: "ok" },
          { pluginId: "max-for-live-grain", slot: 1, enabled: true, status: "ok" },
        ],
        durationBars: 96,
      },
      {
        id: "t-vox",
        name: "Vox_Lead",
        kind: "audio",
        color: "#e11d48",
        freezeStatus: "stem",
        plugins: [
          { pluginId: "fabfilter-pro-q3", slot: 0, enabled: true, status: "frozen-away" },
          { pluginId: "rc20", slot: 1, enabled: true, status: "frozen-away" },
        ],
        durationBars: 88,
        notes: "Ben vocal take 3 — printed with RC-20 color",
      },
      {
        id: "t-vox-harm",
        name: "Vox_Harm",
        kind: "audio",
        color: "#fb7185",
        freezeStatus: "live",
        plugins: [
          { pluginId: "soundtoys-echoboy", slot: 0, enabled: true, status: "ok" },
          { pluginId: "valhalla-vintageverb", slot: 1, enabled: true, status: "ok" },
        ],
        durationBars: 40,
      },
      {
        id: "t-fx",
        name: "Tape_Hiss",
        kind: "audio",
        color: "#a1a1aa",
        freezeStatus: "stem",
        plugins: [{ pluginId: "rc20", slot: 0, enabled: true, status: "frozen-away" }],
        durationBars: 96,
      },
    ],
    files: [
      {
        id: "f1",
        path: "Such_Great_Heights.als",
        kind: "project",
        sizeBytes: 2_840_000,
      },
      {
        id: "f2",
        path: "Samples/Imported/Vox_Lead_T3.wav",
        kind: "audio",
        sizeBytes: 48_200_000,
      },
      {
        id: "f3",
        path: "Samples/Processed/Freeze/Kit_Main_Freeze.wav",
        kind: "freeze",
        sizeBytes: 32_100_000,
      },
      {
        id: "f4",
        path: "Samples/Processed/Freeze/Vox_Lead_Freeze.wav",
        kind: "freeze",
        sizeBytes: 41_000_000,
      },
      {
        id: "f5",
        path: "Samples/Processed/Freeze/Tape_Hiss_Freeze.wav",
        kind: "freeze",
        sizeBytes: 18_400_000,
      },
      {
        id: "f6",
        path: "MIDI/Lead_Heights.mid",
        kind: "midi",
        sizeBytes: 12_400,
      },
      {
        id: "f7",
        path: "Ableton Project Info/Project.cfg",
        kind: "other",
        sizeBytes: 420,
      },
      {
        id: "f8",
        path: "Backup/Such_Great_Heights [2024-11-02].als",
        kind: "project",
        sizeBytes: 2_610_000,
      },
    ],
    commits: [
      {
        id: "c-sgh-1",
        shortId: "a1b2c3d",
        message: "Initial Live set — drums + bass sketch",
        authorId: "u-ben",
        createdAt: daysAgo(120),
        kind: "init",
        filesChanged: 4,
        pluginsDetected: 3,
        tracksFrozen: 0,
        summary: "Created Ableton project, imported kick sketch",
      },
      {
        id: "c-sgh-2",
        shortId: "e4f5g6h",
        message: "Add Operator bass + Wavetable pad; freeze drums for Jimmy",
        authorId: "u-ben",
        createdAt: daysAgo(110),
        kind: "freeze",
        parentId: "c-sgh-1",
        filesChanged: 6,
        pluginsDetected: 5,
        tracksFrozen: 1,
        summary: "Pre-commit freeze on Kit_Main so L.A. can open without Drum Rack samples",
      },
      {
        id: "c-sgh-3",
        shortId: "i7j8k9l",
        message: "Serum lead + EchoBoy — electronics pass from Jimmy",
        authorId: "u-jimmy",
        createdAt: daysAgo(95),
        kind: "push",
        parentId: "c-sgh-2",
        filesChanged: 8,
        pluginsDetected: 9,
        tracksFrozen: 1,
        summary: "Added third-party chain on Lead_Heights (not yet frozen)",
      },
      {
        id: "c-sgh-4",
        shortId: "m0n1o2p",
        message: "Vocal take 3 printed with RC-20; stem Vox_Lead",
        authorId: "u-ben",
        createdAt: daysAgo(40),
        kind: "freeze",
        parentId: "c-sgh-3",
        filesChanged: 5,
        pluginsDetected: 11,
        tracksFrozen: 3,
        summary: "Freeze hook exported Vox_Lead + Tape_Hiss stems",
      },
      {
        id: "c-sgh-5",
        shortId: "q3r4s5t",
        message: "Harmonies + space on Vox_Harm — needs freeze before Taylor mix",
        authorId: "u-jenny",
        createdAt: daysAgo(1, 3),
        kind: "push",
        parentId: "c-sgh-4",
        filesChanged: 3,
        pluginsDetected: 11,
        tracksFrozen: 3,
        summary: "Open freeze items: Lead_Heights, Pad_Cloud, Bass_Analog, Vox_Harm",
      },
    ],
  },
  {
    id: "song-the-district-sleeps",
    ownerId: "u-jimmy",
    slug: "the-district-sleeps-alone",
    title: "The District Sleeps Alone Tonight",
    description:
      "Glitch bed from Jimmy, melody from Ben. Private while we sort the Max devices.",
    visibility: "private",
    daw: "ableton",
    bpm: 136,
    key: "C minor",
    timeSignature: "4/4",
    albumId: "album-give-up",
    tags: ["glitch", "private", "wip"],
    createdAt: daysAgo(80),
    updatedAt: daysAgo(2),
    starCount: 12,
    forkCount: 0,
    coverHue: 280,
    freezeReady: true,
    pluginIds: [
      "ableton-eq8",
      "ableton-simpler",
      "max-for-live-grain",
      "max-for-live-lfo",
      "decapitator",
      "fabfilter-pro-c2",
    ],
    collaborators: [
      { userId: "u-jimmy", role: "owner", joinedAt: daysAgo(80) },
      { userId: "u-ben", role: "writer", joinedAt: daysAgo(78) },
    ],
    tracks: [
      {
        id: "t2-glitch",
        name: "Glitch_Bed",
        kind: "midi",
        color: "#6366f1",
        freezeStatus: "frozen",
        plugins: [
          { pluginId: "max-for-live-grain", slot: 0, enabled: true, status: "frozen-away" },
          { pluginId: "max-for-live-lfo", slot: 1, enabled: true, status: "frozen-away" },
        ],
      },
      {
        id: "t2-vox",
        name: "Vox_District",
        kind: "audio",
        color: "#f43f5e",
        freezeStatus: "stem",
        plugins: [
          { pluginId: "decapitator", slot: 0, enabled: true, status: "frozen-away" },
          { pluginId: "fabfilter-pro-c2", slot: 1, enabled: true, status: "frozen-away" },
        ],
      },
      {
        id: "t2-keys",
        name: "Keys_Night",
        kind: "midi",
        color: "#22c55e",
        freezeStatus: "frozen",
        plugins: [{ pluginId: "ableton-simpler", slot: 0, enabled: true, status: "ok" }],
      },
    ],
    files: [
      {
        id: "f2-1",
        path: "District_Sleeps.als",
        kind: "project",
        sizeBytes: 1_920_000,
      },
      {
        id: "f2-2",
        path: "Samples/Processed/Freeze/Glitch_Bed_Freeze.wav",
        kind: "freeze",
        sizeBytes: 28_000_000,
      },
      {
        id: "f2-3",
        path: "Samples/Processed/Freeze/Vox_District_Freeze.wav",
        kind: "freeze",
        sizeBytes: 36_500_000,
      },
    ],
    commits: [
      {
        id: "c-dsa-1",
        shortId: "d1s2t3",
        message: "Scaffold private set",
        authorId: "u-jimmy",
        createdAt: daysAgo(80),
        kind: "init",
        filesChanged: 2,
        pluginsDetected: 2,
        tracksFrozen: 0,
      },
      {
        id: "c-dsa-2",
        shortId: "u4v5w6",
        message: "Freeze Max devices + Decapitator vocal for Ben",
        authorId: "u-jimmy",
        createdAt: daysAgo(2),
        kind: "freeze",
        parentId: "c-dsa-1",
        filesChanged: 5,
        pluginsDetected: 6,
        tracksFrozen: 3,
        summary: "Collaborator-safe — all third-party chains frozen",
      },
    ],
  },
  {
    id: "song-night-drive",
    ownerId: "u-taylor",
    slug: "night-drive-sketch",
    title: "Night Drive (sketch)",
    description:
      "Flat folder from a Logic bounce + Ableton re-amp. No .als required — any DAW can drop stems here.",
    visibility: "public",
    daw: "folder",
    bpm: 98,
    key: "F# minor",
    timeSignature: "4/4",
    tags: ["sketch", "stems", "folder"],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(0, 8),
    starCount: 214,
    forkCount: 18,
    coverHue: 160,
    freezeReady: true,
    pluginIds: ["ableton-eq8", "fabfilter-pro-q3", "valhalla-vintageverb"],
    collaborators: [
      { userId: "u-taylor", role: "owner", joinedAt: daysAgo(14) },
      { userId: "u-maya", role: "mixer", joinedAt: daysAgo(10) },
    ],
    tracks: [
      {
        id: "t3-drums",
        name: "Drums_Stem",
        kind: "audio",
        color: "#ea580c",
        freezeStatus: "stem",
        plugins: [],
      },
      {
        id: "t3-bass",
        name: "Bass_Stem",
        kind: "audio",
        color: "#2563eb",
        freezeStatus: "stem",
        plugins: [],
      },
      {
        id: "t3-synths",
        name: "Synths_Bus",
        kind: "audio",
        color: "#7c3aed",
        freezeStatus: "stem",
        plugins: [
          { pluginId: "fabfilter-pro-q3", slot: 0, enabled: true, status: "frozen-away" },
        ],
      },
      {
        id: "t3-vox",
        name: "Guide_Vox",
        kind: "audio",
        color: "#e11d48",
        freezeStatus: "stem",
        plugins: [
          { pluginId: "valhalla-vintageverb", slot: 0, enabled: true, status: "frozen-away" },
        ],
      },
    ],
    files: [
      { id: "f3-1", path: "README.txt", kind: "other", sizeBytes: 890 },
      { id: "f3-2", path: "stems/Drums_Stem.wav", kind: "audio", sizeBytes: 52_000_000 },
      { id: "f3-3", path: "stems/Bass_Stem.wav", kind: "audio", sizeBytes: 48_000_000 },
      { id: "f3-4", path: "stems/Synths_Bus.wav", kind: "audio", sizeBytes: 51_200_000 },
      { id: "f3-5", path: "stems/Guide_Vox.wav", kind: "audio", sizeBytes: 44_100_000 },
      { id: "f3-6", path: "midi/chords.mid", kind: "midi", sizeBytes: 4_200 },
      { id: "f3-7", path: "ref/Night_Drive_Rough.mp3", kind: "audio", sizeBytes: 6_200_000 },
    ],
    commits: [
      {
        id: "c-nd-1",
        shortId: "n1d2r3",
        message: "Drop Logic stem folder + guide vocal",
        authorId: "u-taylor",
        createdAt: daysAgo(14),
        kind: "init",
        filesChanged: 6,
        pluginsDetected: 0,
        tracksFrozen: 4,
        summary: "Flat-folder project — no Live set, fully portable",
      },
      {
        id: "c-nd-2",
        shortId: "v4w5x6",
        message: "Maya: synth bus polish (printed)",
        authorId: "u-maya",
        createdAt: daysAgo(0, 8),
        kind: "push",
        parentId: "c-nd-1",
        filesChanged: 2,
        pluginsDetected: 3,
        tracksFrozen: 4,
      },
    ],
  },
  {
    id: "song-coastal",
    ownerId: "u-maya",
    slug: "coastal-hum",
    title: "Coastal Hum",
    description: "Field recordings + soft pads. Public demo of a single-artist song with plugin report.",
    visibility: "public",
    daw: "ableton",
    bpm: 72,
    key: "A major",
    timeSignature: "3/4",
    tags: ["ambient", "field-recording"],
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
    starCount: 421,
    forkCount: 31,
    coverHue: 190,
    freezeReady: true,
    pluginIds: [
      "ableton-wavetable",
      "ableton-reverb",
      "valhalla-vintageverb",
      "ozone-imager",
    ],
    collaborators: [{ userId: "u-maya", role: "owner", joinedAt: daysAgo(30) }],
    tracks: [
      {
        id: "t4-field",
        name: "Field_Shore",
        kind: "audio",
        color: "#0ea5e9",
        freezeStatus: "stem",
        plugins: [{ pluginId: "ozone-imager", slot: 0, enabled: true, status: "frozen-away" }],
      },
      {
        id: "t4-pad",
        name: "Pad_Slow",
        kind: "midi",
        color: "#14b8a6",
        freezeStatus: "frozen",
        plugins: [
          { pluginId: "ableton-wavetable", slot: 0, enabled: true, status: "ok" },
          { pluginId: "valhalla-vintageverb", slot: 1, enabled: true, status: "frozen-away" },
        ],
      },
    ],
    files: [
      { id: "f4-1", path: "Coastal_Hum.als", kind: "project", sizeBytes: 1_100_000 },
      {
        id: "f4-2",
        path: "Samples/Imported/Shore_01.wav",
        kind: "sample",
        sizeBytes: 88_000_000,
      },
      {
        id: "f4-3",
        path: "Samples/Processed/Freeze/Pad_Slow_Freeze.wav",
        kind: "freeze",
        sizeBytes: 22_000_000,
      },
    ],
    commits: [
      {
        id: "c-ch-1",
        shortId: "c0a5ta",
        message: "Import shore takes + freeze pad for share",
        authorId: "u-maya",
        createdAt: daysAgo(30),
        kind: "init",
        filesChanged: 4,
        pluginsDetected: 4,
        tracksFrozen: 2,
      },
    ],
  },
  {
    id: "song-collab-demo",
    ownerId: "u-ben",
    slug: "you-and-taylor",
    title: "You + Taylor (demo collab)",
    description:
      "Template for the Postal Service workflow: you work here, Taylor opens a frozen-safe set on their machine.",
    visibility: "private",
    daw: "ableton",
    bpm: 118,
    key: "E minor",
    timeSignature: "4/4",
    tags: ["collab", "template"],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(0, 2),
    starCount: 3,
    forkCount: 1,
    coverHue: 45,
    freezeReady: false,
    pluginIds: [
      "ableton-eq8",
      "ableton-operator",
      "serum2",
      "uad-1176",
      "kontakt",
      "omnisphere",
    ],
    collaborators: [
      { userId: "u-ben", role: "owner", joinedAt: daysAgo(3) },
      { userId: "u-taylor", role: "producer", joinedAt: daysAgo(2) },
    ],
    tracks: [
      {
        id: "t5-drums",
        name: "Drums",
        kind: "midi",
        color: "#c2410c",
        freezeStatus: "live",
        plugins: [{ pluginId: "kontakt", slot: 0, enabled: true, status: "ok" }],
      },
      {
        id: "t5-bass",
        name: "Bass",
        kind: "midi",
        color: "#1d4ed8",
        freezeStatus: "live",
        plugins: [
          { pluginId: "ableton-operator", slot: 0, enabled: true, status: "ok" },
          { pluginId: "uad-1176", slot: 1, enabled: true, status: "missing" },
        ],
        notes: "Taylor does not have UAD — must freeze",
      },
      {
        id: "t5-keys",
        name: "Keys_Omni",
        kind: "midi",
        color: "#7c3aed",
        freezeStatus: "live",
        plugins: [{ pluginId: "omnisphere", slot: 0, enabled: true, status: "ok" }],
      },
      {
        id: "t5-lead",
        name: "Lead_Serum",
        kind: "midi",
        color: "#db2777",
        freezeStatus: "live",
        plugins: [{ pluginId: "serum2", slot: 0, enabled: true, status: "ok" }],
      },
    ],
    files: [
      { id: "f5-1", path: "You_And_Taylor.als", kind: "project", sizeBytes: 1_450_000 },
      {
        id: "f5-2",
        path: "Samples/Imported/scratch_vox.wav",
        kind: "audio",
        sizeBytes: 12_000_000,
      },
    ],
    commits: [
      {
        id: "c-yt-1",
        shortId: "y0u1t2",
        message: "Invite Taylor + drop first sketch",
        authorId: "u-ben",
        createdAt: daysAgo(3),
        kind: "init",
        filesChanged: 2,
        pluginsDetected: 6,
        tracksFrozen: 0,
        summary: "4 tracks need freeze before collaborator-safe open",
      },
    ],
  },
];

export const ALBUMS: Album[] = [
  {
    id: "album-give-up",
    ownerId: "u-ben",
    slug: "give-up",
    title: "Give Up",
    description:
      "An album built the long way — songs mailed as frozen Live sets, not hard drives full of missing plugs.",
    visibility: "public",
    songIds: ["song-such-great-heights", "song-the-district-sleeps"],
    coverHue: 220,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(1),
  },
];

export const ACTIVITY: ActivityItem[] = [
  {
    id: "a1",
    kind: "push",
    actorId: "u-jenny",
    songId: "song-such-great-heights",
    message: "pushed harmonies on Vox_Harm",
    createdAt: daysAgo(1, 3),
  },
  {
    id: "a2",
    kind: "freeze",
    actorId: "u-jimmy",
    songId: "song-the-district-sleeps",
    message: "froze Max devices for collaborator-safe open",
    createdAt: daysAgo(2),
  },
  {
    id: "a3",
    kind: "push",
    actorId: "u-maya",
    songId: "song-night-drive",
    message: "printed synth bus stems",
    createdAt: daysAgo(0, 8),
  },
  {
    id: "a4",
    kind: "invite",
    actorId: "u-ben",
    songId: "song-collab-demo",
    message: "invited Taylor as producer",
    createdAt: daysAgo(2),
  },
  {
    id: "a5",
    kind: "star",
    actorId: "u-taylor",
    songId: "song-such-great-heights",
    message: "starred Such Great Heights",
    createdAt: daysAgo(0, 20),
  },
  {
    id: "a6",
    kind: "album",
    actorId: "u-ben",
    albumId: "album-give-up",
    message: "updated album Give Up",
    createdAt: daysAgo(5),
  },
];

/** Plugins Taylor has installed — used for compatibility checks */
export const TAYLOR_INSTALLED = [
  "ableton-eq8",
  "ableton-compressor",
  "ableton-reverb",
  "ableton-operator",
  "ableton-wavetable",
  "ableton-simpler",
  "ableton-drum-rack",
  "fabfilter-pro-q3",
  "fabfilter-pro-c2",
  "valhalla-vintageverb",
  "rc20",
];
