/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as DesignRouteImport } from './routes/design'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as AlbumsOwnerSlugRouteImport } from './routes/albums/$owner/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SongsOwnerSlugRouteImport } from './routes/songs/$owner/$slug'
import { Route as SongsOwnerSlugIndexRouteImport } from './routes/songs/$owner/$slug/index'
import { Route as SongsOwnerSlugPrepareRouteImport } from './routes/songs/$owner/$slug/prepare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsOwnerSlugRoute = AlbumsOwnerSlugRouteImport.update({
  id: '/albums/$owner/$slug',
  path: '/albums/$owner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsOwnerSlugRoute = SongsOwnerSlugRouteImport.update({
  id: '/songs/$owner/$slug',
  path: '/songs/$owner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsOwnerSlugIndexRoute = SongsOwnerSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SongsOwnerSlugRoute,
} as any)
const SongsOwnerSlugPrepareRoute = SongsOwnerSlugPrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => SongsOwnerSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/design': typeof DesignRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/u/$username': typeof UUsernameRoute
  '/albums/$owner/$slug': typeof AlbumsOwnerSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/songs/$owner/$slug': typeof SongsOwnerSlugRouteWithChildren
  '/songs/$owner/$slug/prepare': typeof SongsOwnerSlugPrepareRoute
  '/songs/$owner/$slug/': typeof SongsOwnerSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/design': typeof DesignRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/u/$username': typeof UUsernameRoute
  '/albums/$owner/$slug': typeof AlbumsOwnerSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/songs/$owner/$slug/prepare': typeof SongsOwnerSlugPrepareRoute
  '/songs/$owner/$slug': typeof SongsOwnerSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/design': typeof DesignRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/u/$username': typeof UUsernameRoute
  '/albums/$owner/$slug': typeof AlbumsOwnerSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/songs/$owner/$slug': typeof SongsOwnerSlugRouteWithChildren
  '/songs/$owner/$slug/prepare': typeof SongsOwnerSlugPrepareRoute
  '/songs/$owner/$slug/': typeof SongsOwnerSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/design'
    | '/explore'
    | '/library'
    | '/login'
    | '/new'
    | '/settings'
    | '/u/$username'
    | '/albums/$owner/$slug'
    | '/api/auth/$'
    | '/songs/$owner/$slug'
    | '/songs/$owner/$slug/prepare'
    | '/songs/$owner/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/design'
    | '/explore'
    | '/library'
    | '/login'
    | '/new'
    | '/settings'
    | '/u/$username'
    | '/albums/$owner/$slug'
    | '/api/auth/$'
    | '/songs/$owner/$slug/prepare'
    | '/songs/$owner/$slug'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/design'
    | '/explore'
    | '/library'
    | '/login'
    | '/new'
    | '/settings'
    | '/u/$username'
    | '/albums/$owner/$slug'
    | '/api/auth/$'
    | '/songs/$owner/$slug'
    | '/songs/$owner/$slug/prepare'
    | '/songs/$owner/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DesignRoute: typeof DesignRoute
  ExploreRoute: typeof ExploreRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  SettingsRoute: typeof SettingsRoute
  UUsernameRoute: typeof UUsernameRoute
  AlbumsOwnerSlugRoute: typeof AlbumsOwnerSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SongsOwnerSlugRoute: typeof SongsOwnerSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$owner/$slug': {
      id: '/albums/$owner/$slug'
      path: '/albums/$owner/$slug'
      fullPath: '/albums/$owner/$slug'
      preLoaderRoute: typeof AlbumsOwnerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$owner/$slug': {
      id: '/songs/$owner/$slug'
      path: '/songs/$owner/$slug'
      fullPath: '/songs/$owner/$slug'
      preLoaderRoute: typeof SongsOwnerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$owner/$slug/': {
      id: '/songs/$owner/$slug/'
      path: '/'
      fullPath: '/songs/$owner/$slug/'
      preLoaderRoute: typeof SongsOwnerSlugIndexRouteImport
      parentRoute: typeof SongsOwnerSlugRoute
    }
    '/songs/$owner/$slug/prepare': {
      id: '/songs/$owner/$slug/prepare'
      path: '/prepare'
      fullPath: '/songs/$owner/$slug/prepare'
      preLoaderRoute: typeof SongsOwnerSlugPrepareRouteImport
      parentRoute: typeof SongsOwnerSlugRoute
    }
  }
}

interface SongsOwnerSlugRouteChildren {
  SongsOwnerSlugPrepareRoute: typeof SongsOwnerSlugPrepareRoute
  SongsOwnerSlugIndexRoute: typeof SongsOwnerSlugIndexRoute
}

const SongsOwnerSlugRouteChildren: SongsOwnerSlugRouteChildren = {
  SongsOwnerSlugPrepareRoute: SongsOwnerSlugPrepareRoute,
  SongsOwnerSlugIndexRoute: SongsOwnerSlugIndexRoute,
}

const SongsOwnerSlugRouteWithChildren = SongsOwnerSlugRoute._addFileChildren(
  SongsOwnerSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DesignRoute: DesignRoute,
  ExploreRoute: ExploreRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  SettingsRoute: SettingsRoute,
  UUsernameRoute: UUsernameRoute,
  AlbumsOwnerSlugRoute: AlbumsOwnerSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SongsOwnerSlugRoute: SongsOwnerSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
